# yamllint disable rule:line-length
---
sudo: required

language: rust

matrix:
  include:
    - os: linux
    - os: windows
    - os: osx
      osx_image: xcode10

cache:
  cargo: true

script:
  - ./scripts/travis.sh 

_github_api_key: &_github_api_key
  api_key:
    secure: "TawuSrKVtwEe4Q0oqrE3xCOlruX9GK4+kOJZtdZUKhurbEvUmLu4Ge7wYKvg6T05nRSMnTHQ3ReeijMQjwtVSxqbUJShNJx3Est/dzgIFpC6MdI6KtxtdCuiKYuJbm4y1b0MncrIYzpvRj/bMxrUjM3HoUz7I0njJkqQ3O3Mcy2PjwDYuo+lHZRcy6El35dW2WXD2cHSUpqChRKnkOnCCmdnX+2if8BtaFaHlGN3L1MsoU9ZGDbzqpi7KuPaa0RJhS+urgbbR8oqALIoigIcqRoSxpMeQ0G0lGzGZcq5kb/xgCUr52aeSKC60zWLwcEfeSrfPlcXfyjaPNvvIHO+M9x3dKjCmGHLtBwVpLzvR5bUHUIQ3RT5V77ssR2L2HXaddrDwuxQl3mFLJ7UE6htjV6qrv9mF9NIku8+SNenMhvJ37CUv5LtBkb2O3B7V43ivwQ4YFBWf8rHpMMlREefztfbna1vc4k0ma/iDu3jcyn6kG/hMzjnD0xA2YXYwmCIpqYAStfIfDbxdsfhYgtF6cBLo88wyf0fvLNCxMcw/mEGI3oz4Zl0Pbq8kTJ/EvTX7XZMnDVTbExSruy5PT6iRoyGpHa9Z93a5WRhKbLO6iUnUHRM6fhDkGybDA06hjqmflzqTU3AF2Zj0O4Tw9bYoGhW5Ui2JFojSFbDwD4coIA="

deploy:
  - provider: releases
    file_glob: true
    file: "revproxy-*windows*.zip"
    skip_cleanup: true
    "on":
      tags: true
      condition: "$TRAVIS_OS_NAME = windows"
    <<: *_github_api_key
  - provider: releases
    file_glob: true
    file: "revproxy-*macos*.tar.gz"
    skip_cleanup: true
    "on":
      tags: true
      condition: "$TRAVIS_OS_NAME = osx"
    <<: *_github_api_key
  - provider: releases
    file_glob: true
    file: "revproxy-*linux*.tar.gz"
    skip_cleanup: true
    "on":
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
    <<: *_github_api_key
...
