[package]
name = "rev-proxy"
version = "1.2.2-alpha.0"
authors = ["Swift Navigation <dev@swiftnav.com>"]
edition = "2018"
publish = false

[dependencies]
warp = "0.3"
warp-reverse-proxy = "0.3"
envy = "0.4"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.2", features = ["sync", "macros", "rt-multi-thread"] }
log = "0.4"
env_logger = "0.8"
reqwest = "0.10"
clap = { version = "2", features = [] }
indoc = "1"
once_cell = "1.6"

[dependencies.ctrlc]
version = "3.1"
features = [ "termination",]

[build-dependencies]
vergen = "3"
