pre-release-commit-message = "release: {{crate_name}} {{version}}"
consolidate-commits = false
push = true
publish = false
tag-prefix = ""
tag-message = "rev-proxy release {{version}}"
tag-name = "{{version}}"
